{ ... }:

{
  imports = [
    ./hardware-configuration.nix
    ../../modules/nixos
  ];

  networking.hostName = "dev-nix";

  boot.loader.systemd-boot.enable = false;
  boot.loader.efi.canTouchEfiVariables = false;

  boot.loader.grub = {
    enable = true;
    device = "/dev/sda";
  };

  services.openssh = {
    enable = true;

    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  networking.firewall = {
    enable = true;
    allowedTCPPorts = [];
    interfaces.tailscale0.allowedTCPPorts = [ 22 ];
  };

  users.users.leonl.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO76WnPyQ8sZc+/II8xTbGZngbPTLcUBv3U4oD7RzBaC leonlee20031219@gmail.com"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGIdwNz5OUJY1yw6U7XfgFmxyJmZ0sD0jgkIU0pXa1OI Generated By Termius"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBByEixAK3cvQWyfuXKgx00pcsvFBg9sGU+/v2+Yj6qD leonlee20031219@gmail.com"
  ];
}
