"""Persistent Windows 11 VM: Dockur under Docker Compose, viewed with FreeRDP."""

import argparse
import contextlib
import getpass
import json
import os
from pathlib import Path
import pwd
import re
import shutil
import socket
import stat
import subprocess
import sys
import time
import urllib.error
import urllib.request

from . import vm_session as session


PROJECT = "lsy-windows"
CONTAINER = "lsy-windows"
IMAGE = "docker.io/dockurr/windows"
FREERDP = "xfreerdp"
HOST = "127.0.0.1"
RDP_PORT = 3389
CONSOLE_PORT = 8006
CONSOLE_URL = f"http://{HOST}:{CONSOLE_PORT}/"
RUNTIME = "lsy-windows"
CONFIRMATION = "DELETE WINDOWS"
KVM = "/dev/kvm"
TUN = "/dev/net/tun"
GIB = 1024 ** 3
DEFAULT_RAM, DEFAULT_CPUS, DEFAULT_DISK = 8, 4, 80
# Windows 11 minimums: 4 GiB RAM, two cores and 64 GB storage.
MIN_RAM, MIN_CPUS, MIN_DISK = 4, 2, 64
# The downloaded installer image and setup files need space beyond the disk.
DOWNLOAD_HEADROOM = 10
# Docker's grace period; Dockur turns SIGTERM into an ACPI shutdown request.
STOP_TIMEOUT = 120
READY_CONFIRMATIONS = 2
POLL_INTERVAL = 3
# xfreerdp exits with the server's error info. Closing the window (0), logging
# off (2, 12), idle timeout (3), a replaced connection (5) or Start > Disconnect
# (11) ends the session normally.
SESSION_ENDED = frozenset({0, 2, 3, 5, 11, 12})
# Windows itself dropped the connection, for example while applying display
# scaling; the logon session survives, so reconnect instead of shutting down.
SERVER_DISCONNECT = 1
# Sessions shorter than this count towards the reconnect limit.
STABLE_SESSION = 60
MAX_QUICK_RECONNECTS = 3
# Values accepted by /scale for Store (UWP) applications.
DEVICE_SCALES = (100, 140, 180)
# TPKT + X.224 Connection Request + RDP negotiation request (TLS | CredSSP).
RDP_PROBE = bytes.fromhex("03000013" "0ee00000000000" "0100080003000000")
USERNAME = re.compile(r"[A-Za-z0-9_](?:[A-Za-z0-9._-]{0,18}[A-Za-z0-9_-])?")

COMPOSE_HEADER = "# Generated by lsy windows vm; regenerated on every start.\n"
# Copied to C:\OEM and run once at the end of Windows setup. The startup script
# reconnects the drive at every logon in case the persistent mapping is lost.
INSTALL_BAT = r"""@echo off
rem Generated by lsy windows vm install: map the host's ~/Windows folder as Z:.
set "startup=%ProgramData%\Microsoft\Windows\Start Menu\Programs\StartUp"
(
  echo @echo off
  echo rem Generated by lsy: reconnect the host's ~/Windows folder as Z: at logon.
  echo net use Z: ^>nul 2^>^&1 ^|^| net use Z: \\host.lan\Data /persistent:yes
) > "%startup%\lsy-shared-drive.cmd"
net use Z: \\host.lan\Data /persistent:yes
exit /b 0
"""
# Dockur makes an empty shared folder world-writable (mode 2777) at startup.
SHARED_README = """Files in this folder appear in the Windows 11 VM as drive Z: (\\\\host.lan\\Data).

Keep this note while the folder is otherwise empty: the VM makes an empty
shared folder writable by every local user when it starts.
"""


class Paths:
    def __init__(self, home: Path, config_home: Path):
        self.home = home
        self.config_home = config_home
        self.storage = home / ".windows"
        self.shared = home / "Windows"
        self.config = config_home / "lsy" / "windows"
        self.compose = self.config / "compose.yaml"
        self.credentials = self.config / "credentials.env"
        self.settings = self.config / "settings.json"
        self.oem = self.config / "oem"
        # Optional preferences, possibly Home Manager-managed; kept by remove.
        self.preferences = config_home / "lsy" / "windows.json"


def paths() -> Paths:
    home = Path(os.environ.get("HOME") or pwd.getpwuid(os.getuid()).pw_dir)
    config_home = Path(os.environ.get("XDG_CONFIG_HOME") or home / ".config")
    if not home.is_absolute() or not config_home.is_absolute():
        raise RuntimeError("HOME and XDG_CONFIG_HOME must be absolute paths")
    return Paths(home, config_home)


def shown(path: Path) -> str:
    try:
        return f"~/{path.relative_to(Path.home())}"
    except (ValueError, RuntimeError):
        return str(path)


def failure(error) -> int:
    print(f"lsy: {error}", file=sys.stderr)
    return 1


def notify(message: str, urgency: str = "normal") -> None:
    # Menu and desktop-entry launches have no terminal to print to.
    if sys.stdout.isatty() or shutil.which("notify-send") is None:
        return
    subprocess.run(["notify-send", f"--urgency={urgency}", "--app-name=Windows 11", "Windows 11", message],
                   check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def lifecycle_lock():
    # Blocking: a stop queued behind a start (or vice versa) runs afterwards.
    return session.locked(session.runtime_directory(RUNTIME), "lifecycle.lock", blocking=True)


def session_lock(busy: str):
    return session.locked(session.runtime_directory(RUNTIME), "session.lock", busy=busy)


def ensure_directory(path: Path, mode: int) -> Path:
    path.mkdir(mode=mode, parents=True, exist_ok=True)
    info = path.lstat()
    if not stat.S_ISDIR(info.st_mode) or info.st_uid != os.getuid():
        raise RuntimeError(f"unsafe directory {shown(path)}: expected a directory you own, not a symlink")
    os.chmod(path, mode)
    return path


def write_private(path: Path, text: str, newline: str | None = None) -> None:
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.unlink(missing_ok=True)
    fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
    with os.fdopen(fd, "w", newline=newline) as stream:
        stream.write(text)
    os.replace(temporary, path)


def resource_problems(ram: int, cpus: int, disk: int) -> list[str]:
    problems = []
    memory = os.sysconf("SC_PAGE_SIZE") * os.sysconf("SC_PHYS_PAGES")
    if ram < MIN_RAM:
        problems.append(f"--ram must be at least {MIN_RAM} GiB for Windows 11")
    elif ram * GIB >= memory:
        problems.append(f"--ram {ram} GiB leaves nothing for the host ({memory / GIB:.0f} GiB installed)")
    if cpus < MIN_CPUS:
        problems.append(f"--cpus must be at least {MIN_CPUS} for Windows 11")
    elif cpus > (os.cpu_count() or cpus):
        problems.append(f"--cpus {cpus} exceeds the host's {os.cpu_count()} CPUs")
    if disk < MIN_DISK:
        problems.append(f"--disk must be at least {MIN_DISK} GiB for Windows 11")
    return problems


def is_char_device(path: str) -> bool:
    try:
        return stat.S_ISCHR(os.stat(path).st_mode)
    except OSError:
        return False


def existing_ancestor(path: Path) -> Path:
    while not path.exists():
        path = path.parent
    return path


def has_content(path: Path) -> bool:
    return path.is_dir() and not path.is_symlink() and any(path.iterdir())


def preflight(p: Paths, disk: int) -> list[str]:
    problems = []
    if shutil.which("docker") is None:
        problems.append("docker was not found on PATH")
    else:
        if docker("info", "--format", "{{.ServerVersion}}", capture_output=True).returncode:
            problems.append("cannot reach the Docker daemon; is it running and are you in the docker group?")
        if docker("compose", "version", capture_output=True).returncode:
            problems.append("the docker compose plugin is not available")
    if not is_char_device(KVM):
        problems.append(f"{KVM} is missing; enable hardware virtualisation (VT-x/AMD-V) in firmware")
    if not is_char_device(TUN):
        problems.append(f"{TUN} is missing; load the tun kernel module")
    if shutil.which(FREERDP) is None:
        problems.append(f"{FREERDP} (FreeRDP 3) was not found on PATH")
    # Reusing an existing disk only needs room for installer downloads.
    needed = DOWNLOAD_HEADROOM + (0 if has_content(p.storage) else disk)
    free = shutil.disk_usage(existing_ancestor(p.storage)).free
    if free < needed * GIB:
        problems.append(f"only {free / GIB:.0f} GiB free for {shown(p.storage)}; {needed} GiB needed "
                        "(a smaller --disk needs less)")
    return problems


def password_problem(password: str) -> str | None:
    if not password:
        return "The password must not be empty; Windows refuses blank passwords over RDP."
    # FreeRDP reads one argument per line, so line breaks cannot be passed.
    if not all(character.isprintable() for character in password):
        return "The password must not contain line breaks or other control characters."
    return None


def ask_username() -> str:
    default = pwd.getpwuid(os.getuid()).pw_name
    if not USERNAME.fullmatch(default):
        default = "windows"
    while True:
        username = input(f"Windows username [{default}]: ").strip() or default
        if USERNAME.fullmatch(username):
            return username
        print("Use 1-20 letters, digits, '.', '_' or '-', not ending in '.'.", file=sys.stderr)


def ask_password() -> str:
    while True:
        password = getpass.getpass("Windows password: ")
        problem = password_problem(password)
        if problem:
            print(problem, file=sys.stderr)
        elif getpass.getpass("Confirm password: ") != password:
            print("The passwords do not match.", file=sys.stderr)
        else:
            return password


def compose_definition(p: Paths, settings: dict) -> dict:
    # Compose interpolates "$" everywhere, including paths.
    def escaped(path: Path) -> str:
        return str(path).replace("$", "$$")

    def bind(source: Path, target: str, read_only: bool = False) -> dict:
        # Never let Docker create a missing source as a root-owned directory.
        return {"type": "bind", "source": escaped(source), "target": target,
                "read_only": read_only, "bind": {"create_host_path": False}}

    return {
        "name": PROJECT,
        "services": {
            "windows": {
                "image": IMAGE,
                "container_name": CONTAINER,
                "environment": {
                    "VERSION": "11",
                    "RAM_SIZE": f"{settings['ram']}G",
                    "CPU_CORES": str(settings["cpus"]),
                    "DISK_SIZE": f"{settings['disk']}G",
                },
                # Raw format passes the credentials literally, without interpolation.
                "env_file": [{"path": escaped(p.credentials), "format": "raw"}],
                "devices": [KVM, TUN],
                "cap_add": ["NET_ADMIN"],
                "ports": [
                    f"{HOST}:{CONSOLE_PORT}:8006",
                    f"{HOST}:{RDP_PORT}:3389/tcp",
                    f"{HOST}:{RDP_PORT}:3389/udp",
                ],
                "volumes": [
                    bind(p.storage, "/storage"),
                    bind(p.shared, "/shared"),
                    bind(p.oem, "/oem", read_only=True),
                ],
                # lsy owns the lifecycle; Docker must not restart the VM itself.
                "restart": "no",
                "stop_grace_period": f"{STOP_TIMEOUT}s",
            },
        },
    }


def write_compose(p: Paths, settings: dict) -> None:
    # JSON is valid YAML and needs no escaping beyond Compose interpolation.
    write_private(p.compose, COMPOSE_HEADER + json.dumps(compose_definition(p, settings), indent=2) + "\n")


def read_settings(p: Paths) -> dict:
    settings = json.loads(p.settings.read_text())
    if not all(isinstance(settings.get(key), int) for key in ("ram", "cpus", "disk")):
        raise RuntimeError(f"invalid VM settings in {shown(p.settings)}")
    return settings


def read_credentials(p: Paths) -> tuple[str, str]:
    values = {}
    for line in p.credentials.read_text().split("\n"):
        key, separator, value = line.partition("=")
        if separator:
            values[key] = value
    if not values.get("USERNAME") or not values.get("PASSWORD"):
        raise RuntimeError(f"missing credentials in {shown(p.credentials)}")
    return values["USERNAME"], values["PASSWORD"]


def load_installation(p: Paths) -> tuple[dict, str, str]:
    if not p.settings.is_file():
        raise RuntimeError("the Windows VM is not installed; run lsy windows vm install")
    return read_settings(p), *read_credentials(p)


def docker(*arguments: str, **kwargs):
    return subprocess.run(["docker", *arguments], check=False, **kwargs)


def compose(p: Paths, *arguments: str, **kwargs):
    # Run from the config directory so a compose file in the caller's cwd is never read.
    return docker("compose", "--project-name", PROJECT, "--file", str(p.compose), *arguments,
                  cwd=p.config, **kwargs)


def container_state() -> str | None:
    result = docker("container", "inspect", "--format", "{{.State.Status}}", CONTAINER,
                    capture_output=True, text=True)
    if result.returncode == 0:
        return result.stdout.strip()
    if "no such" in result.stderr.lower():
        return None
    raise RuntimeError(f"cannot query Docker: {result.stderr.strip() or 'docker container inspect failed'}")


def start(p: Paths, settings: dict) -> bool:
    """Start the container if it is not running; return whether it was started."""
    write_compose(p, settings)
    if container_state() == "running":
        return False
    print("Starting the Windows VM...", flush=True)
    if compose(p, "up", "--detach").returncode:
        raise RuntimeError("docker compose could not start the Windows VM")
    return True


def shut_down(p: Paths) -> bool:
    """Gracefully stop and remove the container; return False if already absent."""
    state = container_state()
    if state is None:
        return False
    if state == "running":
        print(f"Shutting down Windows (up to {STOP_TIMEOUT} s)...", flush=True)
    if p.compose.is_file() and p.credentials.is_file():
        result = compose(p, "down", "--timeout", str(STOP_TIMEOUT))
    else:
        # The configuration is gone; address the container directly.
        result = docker("container", "stop", "--time", str(STOP_TIMEOUT), CONTAINER)
        if result.returncode == 0:
            result = docker("container", "rm", CONTAINER)
    if result.returncode or container_state() is not None:
        raise RuntimeError(f"could not stop the {CONTAINER} container; inspect it with docker ps -a")
    return True


def rdp_ready(host: str = HOST, port: int = RDP_PORT, timeout: float = 3.0) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout) as connection:
            connection.sendall(RDP_PROBE)
            reply = b""
            while len(reply) < 11:
                chunk = connection.recv(64)
                if not chunk:
                    break
                reply += chunk
    except OSError:
        return False
    # A TPKT (version 3) packet carrying an X.224 Connection Confirm.
    return len(reply) >= 11 and reply[0] == 3 and reply[5] & 0xF0 == 0xD0


def wait_for_rdp(timeout: float) -> bool:
    # Docker's port proxy accepts TCP before Windows listens, so require real
    # RDP negotiation, repeatedly: Windows restarts while it finishes setup.
    deadline = time.monotonic() + timeout
    confirmations = 0
    while True:
        if container_state() != "running":
            raise RuntimeError(f"the Windows container stopped unexpectedly; see docker logs {CONTAINER}")
        confirmations = confirmations + 1 if rdp_ready() else 0
        if confirmations >= READY_CONFIRMATIONS:
            return True
        if time.monotonic() >= deadline:
            return False
        time.sleep(POLL_INTERVAL)


def compositor_scale() -> float | None:
    """Scale of the focused output in the current Hyprland or Niri session."""
    if os.environ.get("HYPRLAND_INSTANCE_SIGNATURE") and shutil.which("hyprctl"):
        command = ["hyprctl", "-j", "monitors"]
    elif os.environ.get("NIRI_SOCKET") and shutil.which("niri"):
        command = ["niri", "msg", "--json", "focused-output"]
    else:
        return None
    try:
        result = subprocess.run(command, capture_output=True, text=True, timeout=2, check=False)
        output = json.loads(result.stdout)
        if command[0] == "hyprctl":
            scale = float(next(monitor["scale"] for monitor in output if monitor.get("focused")))
        else:
            scale = float(output["logical"]["scale"])
    except (OSError, subprocess.TimeoutExpired, ValueError, KeyError, TypeError, StopIteration):
        return None
    return scale if scale > 0 else None


def read_preferences(p: Paths) -> dict:
    try:
        preferences = json.loads(p.preferences.read_text())
    except FileNotFoundError:
        return {}
    except (OSError, ValueError) as error:
        print(f"lsy: ignoring {shown(p.preferences)}: {error}", file=sys.stderr)
        return {}
    return preferences if isinstance(preferences, dict) else {}


def scale_percent(p: Paths) -> int | None:
    # A pinned percentage wins; otherwise follow the compositor.
    configured = read_preferences(p).get("scale")
    if isinstance(configured, int) and not isinstance(configured, bool) and 100 <= configured <= 500:
        return configured
    if configured is not None:
        print(f"lsy: ignoring scale {configured!r} in {shown(p.preferences)}; use 100-500", file=sys.stderr)
    scale = compositor_scale()
    return min(500, max(100, round(scale * 100))) if scale else None


def scale_arguments(percent: int | None) -> list[str]:
    # Windows applies the client's scale at logon or reconnect; changing it
    # inside an RDP session needs a sign-out.
    if percent is None:
        return []
    device = min(DEVICE_SCALES, key=lambda value: abs(value - percent))
    return [f"/scale-desktop:{percent}", f"/scale:{device}"]


def freerdp_arguments(username: str, password: str, scale: int | None = None) -> list[str]:
    return [
        f"/v:{HOST}:{RDP_PORT}",
        f"/u:{username}",
        f"/p:{password}",
        # Dockur's self-signed certificate changes with each install; RDP is loopback-only.
        "/cert:ignore",
        "+dynamic-resolution",
        "+clipboard",
        "/sound",
        "/microphone",
        "+auto-reconnect",
        # Opens as a normal (tiled) window; Ctrl+Alt+Enter toggles fullscreen.
        "/floatbar:sticky:off,default:visible,show:fullscreen",
        "/title:Windows 11",
        "/wm-class:lsy-windows",
        *scale_arguments(scale),
    ]


def run_freerdp(client: str, username: str, password: str, scale: int | None = None) -> int:
    # Arguments go through stdin, not argv, where other local users could read the password.
    arguments = "\n".join(freerdp_arguments(username, password, scale)) + "\n"
    return subprocess.run([client, "/args-from:stdin"], input=arguments, text=True, check=False).returncode


def connect(client: str, username: str, password: str, scale: int | None, timeout: float) -> int:
    quick_reconnects = 0
    while True:
        started = time.monotonic()
        code = run_freerdp(client, username, password, scale)
        if code != SERVER_DISCONNECT:
            return code
        if time.monotonic() - started >= STABLE_SESSION:
            quick_reconnects = 0
        quick_reconnects += 1
        if quick_reconnects > MAX_QUICK_RECONNECTS:
            print("lsy: Windows keeps closing the connection; giving up.", file=sys.stderr)
            return code
        print("Windows closed the connection; reconnecting...", flush=True)
        notify("Windows closed the connection; reconnecting...")
        if not wait_for_rdp(timeout):
            print("lsy: Windows did not accept RDP again.", file=sys.stderr)
            return code


def console_ready(timeout: float = 2.0) -> bool:
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    try:
        opener.open(CONSOLE_URL, timeout=timeout).close()
    except urllib.error.HTTPError:
        return True
    except OSError:
        return False
    return True


def allocated_gib(path: Path) -> float:
    total = 0
    for root, _, files in os.walk(path):
        for name in files:
            with contextlib.suppress(OSError):
                total += os.lstat(os.path.join(root, name)).st_blocks * 512
    return total / GIB


def install(args: argparse.Namespace) -> int:
    try:
        p = paths()
        if p.settings.exists():
            raise RuntimeError("the Windows VM is already installed; see lsy windows vm status "
                               "(lsy windows vm remove deletes it)")
        if not sys.stdin.isatty():
            raise RuntimeError("install needs an interactive terminal to collect Windows credentials")
        problems = resource_problems(args.ram, args.cpus, args.disk) + preflight(p, args.disk)
        if problems:
            print("lsy: cannot install the Windows VM:", file=sys.stderr)
            for problem in problems:
                print(f"  - {problem}", file=sys.stderr)
            return 1
        if has_content(p.storage):
            print(f"Reusing the existing Windows disk in {shown(p.storage)}; enter its account's credentials.")
        username = ask_username()
        password = ask_password()

        settings = {"ram": args.ram, "cpus": args.cpus, "disk": args.disk}
        ensure_directory(p.storage, 0o700)
        p.shared.mkdir(exist_ok=True)
        if not p.shared.is_dir():
            raise RuntimeError(f"{shown(p.shared)} is not a directory")
        if not any(p.shared.iterdir()):
            (p.shared / "README.txt").write_text(SHARED_README)
        ensure_directory(p.config, 0o700)
        ensure_directory(p.oem, 0o700)
        write_private(p.oem / "install.bat", INSTALL_BAT, newline="\r\n")
        write_private(p.credentials, f"USERNAME={username}\nPASSWORD={password}\n")
        write_compose(p, settings)
        # Written last: its presence marks a complete installation.
        write_private(p.settings, json.dumps(settings, indent=2) + "\n")
        print(f"Configured Windows 11 ({args.ram} GiB RAM, {args.cpus} CPUs, {args.disk} GiB disk) "
              f"in {shown(p.config)}.")
        if args.no_start:
            print("Start the installation later with: lsy windows vm console")
            return 0
        with lifecycle_lock():
            start(p, settings)
        print("Windows is downloading and installing in the background; this can take a while.\n"
              f"Watch progress with: lsy windows vm console ({CONSOLE_URL})\n"
              "Once Windows reaches the desktop, connect with: lsy windows vm launch")
        return 0
    except EOFError:
        print("\nInstallation cancelled.", file=sys.stderr)
        return 1
    except (OSError, RuntimeError, ValueError) as error:
        return failure(error)


def launch(args: argparse.Namespace) -> int:
    try:
        p = paths()
        settings, username, password = load_installation(p)
        client = shutil.which(FREERDP)
        if client is None:
            raise RuntimeError(f"{FREERDP} (FreeRDP 3) was not found on PATH")
        with session_lock("a Windows session is already open"):
            with lifecycle_lock():
                if start(p, settings):
                    notify("Starting Windows...")
            print("Waiting for Windows to accept Remote Desktop connections...", flush=True)
            if not wait_for_rdp(args.timeout):
                # Never stop here: Windows may still be installing.
                raise RuntimeError(f"Windows did not accept RDP within {args.timeout} s; it may still be "
                                   "booting or installing. The VM was left running; watch it with "
                                   "lsy windows vm console")
            try:
                code = connect(client, username, password, scale_percent(p), args.timeout)
            finally:
                if args.keep_alive:
                    print("Windows VM left running; stop it with: lsy windows vm stop")
                else:
                    with lifecycle_lock():
                        shut_down(p)
                    print("Windows VM stopped")
        if code not in SESSION_ENDED:
            message = f"FreeRDP exited with code {code}; check the credentials in {shown(p.credentials)}"
            notify(message, "critical")
            print(f"lsy: {message}", file=sys.stderr)
            return code
        return 0
    except (OSError, RuntimeError, ValueError) as error:
        notify(str(error), "critical")
        return failure(error)


def status(args: argparse.Namespace) -> int:
    try:
        p = paths()
        state = container_state()
        installed = p.settings.is_file()
        if state == "running":
            label = "running" if rdp_ready() else "starting"
        else:
            label = "stopped" if installed else "not installed"
        print(f"Windows VM: {label}")
        if not installed:
            if state is not None:
                print(f"  Container {CONTAINER} exists ({state}); stop it with: lsy windows vm stop")
            print("  Install with: lsy windows vm install")
            return 0 if state == "running" else 1
        settings = read_settings(p)
        print(f"  Resources:     {settings['ram']} GiB RAM, {settings['cpus']} CPUs, {settings['disk']} GiB disk")
        print(f"  Disk:          {shown(p.storage)} ({allocated_gib(p.storage):.1f} GiB allocated)")
        print(f"  Shared folder: {shown(p.shared)} (Z: in Windows)")
        print(f"  Config:        {shown(p.config)}")
        if state == "running":
            print(f"  Console:       {CONSOLE_URL}")
            print(f"  RDP:           {HOST}:{RDP_PORT}")
        if label == "starting":
            print("Windows is booting or still installing; watch it with: lsy windows vm console")
        return 0 if state == "running" else 1
    except (OSError, RuntimeError, ValueError) as error:
        return failure(error)


def stop(args: argparse.Namespace) -> int:
    try:
        p = paths()
        with lifecycle_lock():
            shut_down(p)
        print("Windows VM stopped")
        return 0
    except (OSError, RuntimeError) as error:
        return failure(error)


def console(args: argparse.Namespace) -> int:
    try:
        p = paths()
        settings, _, _ = load_installation(p)
        with lifecycle_lock():
            if start(p, settings):
                print("The VM keeps running until: lsy windows vm stop")
        deadline = time.monotonic() + 30
        while not console_ready():
            if time.monotonic() >= deadline:
                raise RuntimeError(f"the web console at {CONSOLE_URL} did not respond")
            time.sleep(1)
        opener = shutil.which("xdg-open")
        if opener is None:
            print(f"Open {CONSOLE_URL} in a browser.")
            return 0
        subprocess.run([opener, CONSOLE_URL], check=False,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        print(f"Opened {CONSOLE_URL}")
        return 0
    except (OSError, RuntimeError, ValueError) as error:
        return failure(error)


def removal_problems(p: Paths) -> list[str]:
    problems = []
    shared = p.shared.resolve()
    expected = {
        p.storage: p.home.resolve() / ".windows",
        p.config: p.config_home.resolve() / "lsy" / "windows",
    }
    for path, resolved in expected.items():
        if not (path.exists() or path.is_symlink()):
            continue
        info = path.lstat()
        if stat.S_ISLNK(info.st_mode):
            problems.append(f"{shown(path)} is a symlink")
        elif not stat.S_ISDIR(info.st_mode):
            problems.append(f"{shown(path)} is not a directory")
        elif info.st_uid != os.getuid():
            problems.append(f"{shown(path)} is not owned by you")
        elif path.resolve() != resolved:
            problems.append(f"{shown(path)} resolves through a symlink to {path.resolve()}")
        elif shared == resolved or resolved in shared.parents:
            problems.append(f"the shared folder {shown(p.shared)} is inside {shown(path)}")
    # The storage path is passed to docker --mount, which splits on commas.
    if "," in str(p.storage):
        problems.append(f"{shown(p.storage)} contains a comma")
    return problems


def delete_storage(path: Path) -> None:
    try:
        shutil.rmtree(path)
    except PermissionError:
        # Dockur runs as root, so directories it created may not be writable
        # by you. Empty the disk directory from a container, then remove it.
        result = docker("run", "--rm", "--pull", "never", "--network", "none", "--entrypoint", "find",
                        "--mount", f"type=bind,source={path},target=/storage",
                        IMAGE, "/storage", "-xdev", "-mindepth", "1", "-delete")
        if result.returncode:
            raise RuntimeError(f"could not delete root-owned files in {shown(path)}") from None
        shutil.rmtree(path)


def remove(args: argparse.Namespace) -> int:
    try:
        p = paths()
        with session_lock("close the Windows session before removing the VM"), lifecycle_lock():
            problems = removal_problems(p)
            if problems:
                print("lsy: refusing to remove the Windows VM:", file=sys.stderr)
                for problem in problems:
                    print(f"  - {problem}", file=sys.stderr)
                return 1
            state = container_state()
            if state is None and not p.storage.exists() and not p.config.exists():
                print("The Windows VM is not installed; nothing to remove.")
                return 0

            print("This permanently deletes the Windows VM:")
            if state is not None:
                print(f"  - Docker container {CONTAINER} ({state}); Windows is shut down first")
            if p.storage.exists():
                print(f"  - {shown(p.storage)}: the Windows disk, firmware and installer files "
                      f"({allocated_gib(p.storage):.1f} GiB)")
            if p.config.exists():
                print(f"  - {shown(p.config)}: VM configuration and saved credentials")
            print("Preserved:")
            print(f"  - {shown(p.shared)}: the shared folder (Z:) and everything in it")
            print(f"  - Docker image {IMAGE} (docker image rm {IMAGE} deletes it)")
            if p.preferences.exists():
                print(f"  - {shown(p.preferences)}: display preferences")
            try:
                answer = input(f"Type {CONFIRMATION} to confirm: ")
            except EOFError:
                answer = ""
            if answer != CONFIRMATION:
                print("Aborted; nothing was deleted.")
                return 1

            shut_down(p)
            # Re-check: the paths must not have changed while waiting for input.
            problems = removal_problems(p)
            if problems:
                raise RuntimeError(f"refusing to delete files: {'; '.join(problems)}")
            if p.storage.exists():
                delete_storage(p.storage)
            if p.config.exists():
                shutil.rmtree(p.config)
            print(f"Windows VM removed. {shown(p.shared)} was preserved.")
            return 0
    except (OSError, RuntimeError) as error:
        return failure(error)


def register(subparsers) -> None:
    windows = subparsers.add_parser("windows", help="Windows virtual machines")
    windows_commands = windows.add_subparsers(dest="windows_command", required=True)
    parser = windows_commands.add_parser(
        "vm",
        help="Persistent Windows 11 VM (Dockur and FreeRDP)",
        description=(
            f"Persistent Windows 11 VM run by Dockur under Docker Compose and viewed with FreeRDP. "
            f"Its disk lives in ~/.windows; ~/Windows is shared as drive Z:. The web console "
            f"({CONSOLE_URL}) and RDP listen on {HOST} only."
        ),
    )
    commands = parser.add_subparsers(dest="windows_vm_command", required=True)

    install_parser = commands.add_parser(
        "install",
        help="Check requirements, save credentials and start installing Windows",
        description="Check Docker, KVM, TUN, FreeRDP and free space, ask for the Windows account, "
                    "write the configuration and start the unattended Windows installation.",
    )
    install_parser.add_argument("--ram", type=int, default=DEFAULT_RAM, metavar="GIB",
                                help=f"memory in GiB (default: {DEFAULT_RAM})")
    install_parser.add_argument("--cpus", type=int, default=DEFAULT_CPUS, metavar="N",
                                help=f"virtual CPUs (default: {DEFAULT_CPUS})")
    install_parser.add_argument("--disk", type=int, default=DEFAULT_DISK, metavar="GIB",
                                help=f"disk size in GiB (default: {DEFAULT_DISK})")
    install_parser.add_argument("--no-start", action="store_true", help="Configure without starting the VM")
    install_parser.set_defaults(handler=install)

    launch_parser = commands.add_parser(
        "launch",
        help="Start the VM and connect with FreeRDP",
        description="Start the VM if needed, wait until Windows accepts RDP, then open FreeRDP. "
                    "Closing FreeRDP shuts the VM down unless --keep-alive is given.",
    )
    launch_parser.add_argument("--keep-alive", action="store_true",
                               help="Leave the VM running after FreeRDP exits")
    launch_parser.add_argument("--timeout", type=int, default=300, metavar="SECONDS",
                               help="How long to wait for RDP (default: 300)")
    launch_parser.set_defaults(handler=launch)

    for name, handler, help_text in (
        ("status", status, "Report whether the VM is installed, stopped, starting or running"),
        ("stop", stop, "Shut Windows down gracefully"),
        ("console", console, f"Start the VM if needed and open the web console ({CONSOLE_URL})"),
        ("remove", remove, "Delete the VM and ~/.windows after confirmation; keeps ~/Windows"),
    ):
        commands.add_parser(name, help=help_text).set_defaults(handler=handler)
